  name: Integracao Continua 

  on:
    pull_request:
      branches:
        - develop
    push:

  jobs:
    build-deploy:
      runs-on: ubuntu-latest
      env:
        DOCKER_REPOSITORY: vagnerasilva # name of Docker Hub ID
        IMAGE_NAME: testeimagevagner
        IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      steps:
        - name: Git Checkout
          uses: actions/checkout@v2
        
        - name: Ambientando1
          run:
            pwd

        - name: Ambientando2
          run:
            chmod +x ./build.sh
        
        - name: Ambientando3
          run:
            ls -la

        - name: Build Docker Image
          run:
            ./build.sh
    
        - name: List Image
          run:
            docker images "vagnerasilva\/*"

        - name: get scout
          run:
            curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh

        - name: Ambientando4
          run:
            chmod +x ./install-scout.sh

        - name: install scout
          run:
            ./install-scout.sh

        - name: scan scout
          run:
            docker scout quickview vagnerasilva/container-img3