  name: Integracao Continua

  on:
    pull_request:
      branches:
        - develop
    push:

  jobs:
    build-deploy:
      runs-on: ubuntu-latest
      env:
        DOCKER_REPOSITORY: houssemdocker # name of Docker Hub ID
        IMAGE_NAME: webapp
        IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      steps:
        - name: Git Checkout
          uses: actions/checkout@v2
        
        - name: Ambientando1
          run:
            #docker build ./img/ --file ./img/Dockerfile
            pwd
            ls -la

        - name: Ambientando2
          run:
              #docker build ./img/ --file ./img/Dockerfile
            ls -la

        - name: Build Docker Image
          run:
            #docker build ./img/ --file ./img/Dockerfile
            #docker build .
            chmod + x build.sh
            ./build.sh
    
        - name: list Image
          run:
            docker images