  name: Integracao Continua

  on:
    pull_request:
      branches:
        - main
    push:

  jobs:
    executa_linter:
      runs-on: ubuntu-latest
      steps:
        - name: 1. Realiza o Checkout
          uses: actions/checkout@v2
        
        - name: 2. Instala o python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: 3. Instala o Poetry
        - uses: Gr1N/setup-poetry@v7
          with:
            poetry-preview: true
        - run: poetry --version

        - name: 4. Instala as Dependencias
          run: poetry install 
        
        - name: Executa o Black
          run: poetry run black --check app

        - name: Executa o isort
          run: poetry run isort --check app

        - name: Executa o pydocstyle
          run: poetry run pydocstyle app 

        - name: Executa os testes unitarios
          run: poetry run pytest
